modLoader="javafml"
loaderVersion="[47,)" # هنا لازم تناسب نسخة forge بتاعتك
license="MIT"
issueTrackerURL="https://github.com/yourname/yourmod/issues"

[[mods]]
modId="test" # ده لازم يكون نفس الـ MOD_ID في الكود
version="1.0.0"
displayName="Test Mod"
authors="Ghost"
description='''
مود تجريبي للماين كرافت.
'''

# اختيارية
[[dependencies.test]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.test]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
